<a href="https://colab.research.google.com/github/fernandodeeke/python/blob/master/intro_arrays1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<h2> Arrays</h2> <br>
    Fernando Deeke Sasse
</center>

Usaremos a biblioteca do Python chamada numpy:

In [ ]:
import numpy as np

Definimos um array 1-dimensional:

In [ ]:
a = np.array([2,5,7,1,3])

In [ ]:
print(a)

[2 5 7 1 3]


In [ ]:
a

array([2, 5, 7, 1, 3])

Selecionemos componentes do array a:

In [ ]:
a[0]

2

In [ ]:
a[4]

3

Criemos um array (1-dimensional) cujo primeiro elemento é 0 e o último elemento é 10, com intervalo entre elementos de tamanho 2:

In [ ]:
b = np.arange(0,51,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
b[25]

50

**Exercício**. Construa uma array 1-dimensional cujo primeiro elemento é 0 e último elemento é 10 e o intervalo entre os elementos é 0.1;